services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ayacoo\Podigee\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Helper/*'

  Ayacoo\Podigee\Command\UpdateMetadataCommand:
    tags:
      - name: 'console.command'
        command: 'podigee:updateMetadata'
        description: 'Updates the Podigee metadata'
        schedulable: true

  Ayacoo\Podigee\EventListener\ModifyIconForResourcePropertiesListener:
    tags:
      - name: 'event.listener'
        identifier: 'podigee/modify-icon-for-resource'
        event: 'TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent'
